run:

linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  funlen:
    lines: 100
    statements: 50
  cyclomatic_complexity:
    ignores_case_statements: true

linters:
  disable:
    - gochecknoglobals
    - testpackage
    #- gomnd
    #- exhaustive
    - paralleltest
    - exhaustivestruct
    - forbidigo
    - wrapcheck
  enable-all: true
