version: '3'

tasks:
  default:
    desc: Show help messages
    silent: true
    cmds:
      - echo "Welcome to use go-task!"
      - echo
      - |
        echo "Available tasks:"
        task --list | awk 'NR>1 {print "  " $0}'

  gen:
    desc: Generate plugin
    cmds:
      - go build -buildmode=plugin -o output/01_plugin.so plugins/01_plugin.go
      - go build -buildmode=plugin -o output/02_plugin.so plugins/02_plugin.go


  run:
    desc: Run guardhouse locally
    cmds:
      - go run main.go